### ISSUE TITLE
IllegalArgumentException: metric already exists

### ISSUE THREAD

**Issue by gnurik** [addthis/metrics-reporter-config#42]
looks like commit b8cbf4dfd96df54926d4ef731fdd8c5251eee4cb seems to cause a problem with dropwizard whose Bootstrap class does something very similar  `this.getMetricRegistry().register("jvm.attribute", new JvmAttributeGaugeSet());` and thus causes an exception when `enableAll` is called:

```
Exception in thread "main" java.lang.IllegalArgumentException: A metric named jvm.attribute.vendor already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:389)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
	at com.addthis.metrics3.reporter.config.ReporterConfig.registerJvmMetrics(ReporterConfig.java:306)
```

Should refactor registering jvm metrics into a separate class that is not automatically called here. It also makes sense to decouple registering specific metrics from registering specific metrics reporters.

**Comment by gnurik** [comment]
@lucky I wrote this ticket to track the issue I raised, pls grab.

**Comment by lucky** [comment]
I don't think I can assign myself because I'm not a part of this org, but I'm planning to tackle this

**Comment by gnurik** [comment]
@lucky we're actually blocked by this issue now, can you fix plz?

**Comment by gnurik** [comment]
works now, thx!

**Comment by lucky** [comment]
Good to hear it, and sorry for the delay.
