### ISSUE TITLE
Statsd reporter error on cassandra 3.0.5

### ISSUE THREAD

**Issue by nithinmohan** [addthis/metrics-reporter-config#53]
I am getting this error on cassandra startup

`
INFO  11:02:37 Trying to load metrics-reporter-config from file: metrics-reporter-statsd.yaml
WARN  11:02:37 Failed to load metrics-reporter-config, metric sinks will not be activated
org.yaml.snakeyaml.constructor.ConstructorException: null; Can't construct a java object for tag:yaml.org,2002:com.addthis.metrics3.reporter.config.ReporterConfig; exception=Cannot create property=statsd for JavaBean=com.addthis.metrics3.reporter.config.ReporterConfig@752637ed; Unable to find property 'statsd' on class: com.addthis.metrics3.reporter.config.ReporterConfig;  in 'reader', line 1, column 1:
    statsd:
    ^
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412) ~[snakeyaml-1.11.jar:na]
	at com.addthis.metrics.reporter.config.AbstractReporterConfig.loadFromFile(AbstractReporterConfig.java:41) ~[reporter-config-base-3.0.0.jar:3.0.0]
	at com.addthis.metrics3.reporter.config.ReporterConfig.loadFromFile(ReporterConfig.java:249) ~[reporter-config3-3.0.0.jar:3.0.0]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:351) [apache-cassandra-3.0.5.jar:3.0.5]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551) [apache-cassandra-3.0.5.jar:3.0.5]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:679) [apache-cassandra-3.0.5.jar:3.0.5]
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=statsd for JavaBean=com.addthis.metrics3.reporter.config.ReporterConfig@752637ed; Unable to find property 'statsd' on class: com.addthis.metrics3.reporter.config.ReporterConfig
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331) ~[snakeyaml-1.11.jar:na]
	... 10 common frames omitted
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'statsd' on class: com.addthis.metrics3.reporter.config.ReporterConfig
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:308) ~[snakeyaml-1.11.jar:na]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240) ~[snakeyaml-1.11.jar:na]
	... 12 common frames omitted
INFO  11:02:37 Waiting for gossip to settle before accepting client requests...
`

Cassandra version:3.0.5

Other libraries:
metrics2-statsd-4.1.2.jar
metrics3-statsd-4.1.0.jar
metrics-core-3.1.0.jar
metrics-logback-3.1.0.jar
metrics-statsd-common-4.1.0.jar

Same setup worked on cassandra 3.11.3

I have verified that there is no error in config yaml file. I am doubting I need to change the version of libraries.

**Comment by nithinmohan** [comment]
Found out that the reporter config jar which ships with cassandra 3.0.5 doesn't have statsd support.
Closing this, but if anyone know a fix for this without upgrading cassandra, please comment
